---
include:
  - board: nice_nano_v2
    shield: keyball44_left nice_oled autocorrect_adapter
  - board: nice_nano_v2
    shield: keyball44_right nice_oled autocorrect_adapter
  - board: nice_nano_v2
    shield: settings_reset
