file_format: "1"
id: keyball44
name: Keyball44
type: shield
url: https://github.com/Yowkees/keyball
requires: [pro_micro]
features:
  - keys
  - pointer
  - underglow
siblings:
  - keyball44_left
  - keyball44_right
