manifest:
  remotes:
    - name: valkride
      url-base: https://github.com/valkride
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: valkride
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: valkride
      revision: main
    - name: zmk-nice-oled
      remote: valkride
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
  self:
    path: config