manifest:
  remotes:
    - name: valkride
      url-base: https://github.com/valkride
  projects:
    - name: zmk
      remote: valkride
      revision: main
      import: app/west.yml
    - name: zmk-autocorrect-module
      remote: valkride
      revision: main
  self:
    path: config