manifest:
  remotes:
    - name: valkride
      url-base: https://github.com/valkride
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk-pmw3610-driver
      remote: valkride
      revision: main
    - name: zmk-nice-oled
      remote: valkride
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
  self:
    path: config
