on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    # No 'with' inputs needed as 'pre-run' is not supported by the referenced workflow
